### ISSUE TITLE
Wallet connected to Dojo takes a minute to sync

### ISSUE THREAD

**Issue by Relaxo143** [Samourai-Wallet/samourai-dojo#86] opened 2019-10-19 11:50 UTC
**Describe the issue**
Dojo takes a lot of time to sync. It started happening only recently. The biggest bottleneck seems to be the import request/command. It takes more than 40 seconds. Why does it import the same addresses again and again though? Shouldn't this be a one time process? When I send a transaction it also takes 40+ secs to show up in the wallet.

**Screenshots**
![dojo](https://user-images.githubusercontent.com/42069389/67144457-1777b400-f27f-11e9-8036-c05a73619600.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu v18.04.2
 - Dojo Version v1.0.0
 - Dojo Advanced Setups used: external bitcoind

**Additional context**
The VM runs on 4 cores and has 2.5 GiB RAM. It uses ~1.8GiB

**Comment by LaurentMT** [comment] 2019-10-20 20:15
These addresses are related to your Paynyms. I suspect that the long delay is caused by the use of bitcoind as the data source used by Dojo for imports/rescans (the scantxoutset provided by bitcoind function isn't really fast). There are some new features in the pipes that should definitely improve this part (probably released in v1.4).

**Comment by Relaxo143** [comment] 2019-10-21 10:06
Isn't that the purpose of dojo? What could I use as data source if not bitcoind? Also I haven't received any funds via paynyms. Weird.

**Comment by LaurentMT** [comment] 2019-10-21 10:46
Current versions of Dojo track the activity of your wallet but they don't index the activity of all addresses that have been active on the blockchain. But sometimes, your wallet will need that Dojo checks if an address has some past activity (when you sweep an external privkey with your wallet, when your wallet checks if payments were received by your Paynym, etc). 

This is why current versions of Dojo need an "external" data source. Currently, Dojo supports 2 possible data sources: your local bitcoind or OXT. OXT is provided as a backup solution but its use isn't recommended for privacy reasons. 

As I wrote in my previous comment, a third solution is in the pipes. It will the provide the best of both worlds (i.e. the privacy of a local data source without the limitations and slowness of the scantxoutset function provided by bitcoind). The tradeoff is that it will require some additional disk space (around 50GB).

**Comment by Relaxo143** [comment] 2019-10-21 11:22
Update: In my paynyms menu It said following: 1 (the samourai donations paynym), but I had never actually sent the special transaction. I archived the paynym and now my wallet takes 5 secs to sync again. Thanks for pointing me in the right direction. Maybe there should be a warning about using dojo with paynyms? It slows down the sync time by 8 times and makes the wallet almost unusable. Also off topic, but what is the difference between following a paynym with and without the special tx?

**Comment by LaurentMT** [comment] 2019-10-21 14:03
Thanks to you. This kind of feedback is always useful to identify the pain points that should be prioritized.

For what it worths, we're also going to check if we can provide in next Dojo version (1.3) a first solution mitigating this issue for Dojo users.

**Comment by kenshin-samourai** [comment] 2019-10-21 18:44
code in branch fix_force_import_bip47_addr should mitigate the issue for Dojo users.

will be merged in develop for QA of v1.3.

**Closed** 2019-12-10 12:41 UTC
Labels: enhancement, support
